apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-client
spec:
  selector:
    matchLabels:
      app: zookeeper-client
  replicas: 3
  template:
    metadata:
      labels:
        app: zookeeper-client
    spec:
      containers:
        - name: zookeeper-client
          image: leonardorocha1990/zookeeper-client:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 30
#            failureThreshold: 10
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 30
#            failureThreshold: 10