apiVersion: v1
kind: Service
metadata:
  name: zookeeper-client
  labels:
    app: zookeeper-client
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30712
      protocol: TCP
      name: zookeeper-client
  selector:
    app: zookeeper-client